title: Sunghyun Jin's Personal Deadlines
description: Countdowns to deadlines.
author: Sunghyun Jin

domain: "https://mcsmonk.github.io/deadlines"
baseurl: ""

twitter_username: mcsmonk_shj
github_username: mcsmonk
github_repo: deadlines
ga_id: UA-155268748-1

markdown: kramdown
